// Server-only mapping. Feishu media tokens are intentionally kept out of the
// browser bundle. Entries without a Feishu token continue to use the R2
// fallback configured in public/media/manifest.json.
export const FEISHU_VIDEO_SOURCES = {
  "ai-manga-01": { kind: "media", token: "DmaObePvuoC9k0xU2YJczj7EnCd" },
  "ai-manga-02": { kind: "media", token: "PeZ3bhWB5o7pbMx3P9ccsceQnqe" },
  "ai-manga-03": { kind: "media", token: "AsUub0BnUolgqvxKv1ncDHKAnue" },
  "ai-manga-04": { kind: "media", token: "Fs0cbbREeolSoqxkPB5cwZeUnYd" },
  "ai-manga-05": { kind: "media", token: "JJbIb7oQXoxD9JxLWzUcdvoBnLc" },
  "ai-manga-06": { kind: "media", token: "QZzubcLt7o1OsMxmNFOcfRM2nph" },
  "ai-manga-07": { kind: "media", token: "MUlubTh2QoN5OJxxwKIcIkpznYe" },
  "ai-manga-08": { kind: "media", token: "CbyGbAEIHokXR4xW0LEcWM6dnac" },
  "documentary-trailers-01": { kind: "media", token: "Nq6Rbo4UfoPGJSxvuGHcHn1nnGb" },
  "documentary-trailers-02": { kind: "media", token: "DeSEbwHYJo4afvxMvodcV26cnld" },
  "documentary-trailers-03": { kind: "media", token: "SL2tb3ZJXovPcPxw19HcOCvnnEh" },
  "documentary-trailers-04": { kind: "media", token: "O1NnbjctqomMIQxlCZjcul59nCb" },
  "documentary-trailers-05": { kind: "media", token: "IxGVbFea0ooDTzxp7Ajc41M0n4d" },
  "documentary-trailers-07": { kind: "media", token: "GxPWbUaqxorGYJxv4f2cRQ3rnAg" },
  "documentary-trailers-06": { kind: "media", token: "LSgkb6M02ornONxIlLLcvqGEnue" },
  "guangxi-01": { kind: "media", token: "Cbj4bjLHyomifYxkJ4pcNppJnpe" },
  "palace-01": { kind: "media", token: "CbS8bR5k6oT5cjxnqCvc6U2dnGg" },
  "palace-02": { kind: "media", token: "Ybdhbeaxdos6IkxEWoocrHZgnRb" },
  "palace-03": { kind: "media", token: "ZQRzbiwKgoMSbkxWjekcmQRfn4f" },
  "palace-04": { kind: "media", token: "TUHAbPcrLofX5Vxg6B9c2Q8An5b" },
  "palace-05": { kind: "media", token: "SNGNbO2oSoYYHsxxetncxoivnRb" },
  "xiangxin-01": { kind: "media", token: "D3YMby37yorbuSxKAGCcD0AjnIh" },
  "xiangxin-02": { kind: "media", token: "EjkAbH7XUorYocxKSaMc1v5wnig" },
  "xiangxin-03": { kind: "media", token: "UIQjbOf9moqK12xWLLYcFb0mn9b" },
  "xiangxin-04": { kind: "media", token: "OF8ibO4VWo2YQNx8jb6cwt6anYd" },
  "xiangxin-05": { kind: "media", token: "JUrWbJTIxotpaFxaTlJczBmPnUz" },
  "xinhua-02": { kind: "media", token: "VjLbbU81BodhTIxmNt9cVFtAn4c" },
  "xinhua-01": { kind: "media", token: "PgZpbKqwFoMb4txItPMcHuM0nXf" },
  "tibet-01": { kind: "media", token: "XAdDbzupXofZDox1yrxcrFZnn8b" },
  "xiaomi-07": { kind: "media", token: "ZG0ybFvEWoBwqsxojANcxQROnYc" },
  "xiaomi-05": { kind: "media", token: "YoivbBd0XoSdjaxFrsdc0jzDnje" },
  "xiaomi-06": { kind: "media", token: "XkD0bYbRqosYHAxZepEcrk8cngd" },
  "xiaomi-01": { kind: "media", token: "Z1uTbOzxKonCaNxv8Oacf7xGnmh" },
  "xiaomi-02": { kind: "media", token: "GOSqbm9dyoZAm4xfP6Mc5TY8neb" },
  "xiaomi-03": { kind: "media", token: "WRk8bAF2XoPXYWx4ZiXcnMCsncw" },
  "xiaomi-04": { kind: "media", token: "A2A7bc2Bno3j8GxNJ7OcAoI4nJ6" },
  "course-01": { kind: "media", token: "MNPhbZ3z9oAzM9x7BwIcULXpn4e" },
  "course-02": { kind: "media", token: "EqCbbRvETo4356xqhEWcZuMpnfb" },
  "course-05": { kind: "media", token: "F2hBbylYNoyuNHxjoxYcUf2rnDd" },
  "course-04": { kind: "media", token: "UGCibQgukosNGyx26qjctfy6nWc" },
  "course-03": { kind: "media", token: "OwjHbcpcjo4hugxuEd8cjxyyn18" }
};
